Update casa urls
commercialhaskell/pantry pull request #103
Opened 2023-08-11 09:01 UTC by psibi

2023-08-11 09:08 UTC, snoyberg approved these changes
FYI @mpilgrem this is a DevOps change on our side, trying to put the URLs where they belong.

2023-08-11 15:43 UTC, psibi commented
Let's defer merging this till couple of days to see how the new deployment goes on.

2023-08-11 16:47 UTC, mpilgrem requested changes
I think we should retain the lower bound on `hpack`. Other than that, looks good to me.

2023-08-11 16:47 UTC, mpilgrem commented on package.yaml
> +- hpack
I think the lower bound on `hpack` is needed, because of how `pantry` handles 'pretty' Hpack error messages.

2023-08-15 22:28 UTC, mpilgrem commented
@psibi, I rebased on `master`. The (different) lower bound on `hpack` in `master` is now due to the move to `crypton`. Has enough time since deployment now passed to allow a merge?

2023-08-17 04:36 UTC, psibi commented
@mpilgrem Yes, the build is stable now. The reason for the lower bound is because stackage server uses older packages (including cryptonite). That being said - I think this PR is good to merge. The stackage server will be using a different branch of pantry untill we fix it properly: https://github.com/fpco/stackage-server/pull/321/files#diff-0de01f189d384bfbe69e806ef70b1a425b27394dbe2a9d0e62ffd010dda86c03R13

2023-08-17 04:38 UTC, psibi commented
Thanks for rebasing it, please merge it whenever you think is appropriate.

2023-08-17 07:14 UTC, merged