Switch back to hackage.haskell.org
commercialhaskell/pantry pull request #30
Opened 2021-01-20 19:40 UTC by martijnbastiaan

's3.amazonaws.com' is not meant to serve clients around the world, as it
is hosted in the US only. This causes bandwidth to be severely throttled
for, amongst others, European users. This has been observed by users in
the following issue:

  https://github.com/commercialhaskell/stack/issues/2240

At some periods, bandwidth drops to effectively zero, rendering Stack
unusable. Measurements can be found here:

  https://github.com/commercialhaskell/stack/issues/2240#issuecomment-761197177

'hackage.haskell.org' is served from Fastly's CDN, therefore mitigating
these issues.

-----------------

This is part of a [larger effort](https://github.com/commercialhaskell/stack/issues/2240#issuecomment-761812803) to eliminate Stack's reliance on non-CDN resources :). I see @snoyberg reverted an earlier change to move back to hackage.haskell.org, perhaps he could comment on this issue?

2021-01-21 05:52 UTC, snoyberg commented
I moved it back because of instability from Hackage, see https://github.com/commercialhaskell/stack/issues/4473.

If that's truly been resolved at this point, I have no objection to moving back to Hackage by default.

2021-01-21 06:01 UTC, snoyberg requested changes
Can you include a version bump and changelog entry?

2021-01-21 18:33 UTC, martijnbastiaan commented
@snoyberg Done.

2021-01-22 06:16 UTC, snoyberg approved these changes
Thanks!

2021-01-22 06:16 UTC, merged