Fix compatibility with GHC 9
commercialhaskell/pantry pull request #39
Opened 2021-06-29 02:50 UTC by felixonmars

Fixes the following error:

```
[10 of 19] Compiling Pantry.Storage   ( src/Pantry/Storage.hs, dist/build/Pantry/Storage.dyn_o )

src/Pantry/Storage.hs:275:8: error:
    • Couldn't match type: forall env1 a1.
                           HasLogFunc env1 =>
                           ReaderT SqlBackend (RIO env1) a1 -> RIO env1 a1
                     with: ReaderT SqlBackend (RIO env) a -> RIO env a
      Expected: SQLite.Storage
                -> ReaderT SqlBackend (RIO env) a -> RIO env a
        Actual: SQLite.Storage
                -> forall env a.
                   HasLogFunc env =>
                   ReaderT SqlBackend (RIO env) a -> RIO env a
    • In the first argument of ‘flip’, namely ‘SQLite.withStorage_’
      In the first argument of ‘(=<<)’, namely
        ‘flip SQLite.withStorage_ action’
      In the expression:
        flip SQLite.withStorage_ action
          =<< view (P.pantryConfigL . to P.pcStorage)
    • Relevant bindings include
        action :: ReaderT SqlBackend (RIO env) a
          (bound at src/Pantry/Storage.hs:274:13)
        withStorage :: ReaderT SqlBackend (RIO env) a -> RIO env a
          (bound at src/Pantry/Storage.hs:274:1)
    |
275 |   flip SQLite.withStorage_ action =<< view (P.pantryConfigL.to P.pcStorage)
    |        ^^^^^^^^^^^^^^^^^^^
```

2021-06-29 03:15 UTC, snoyberg requested changes

2021-06-29 03:15 UTC, snoyberg commented on src/Pantry/Storage.hs
> +  flip (\x y -> SQLite.withStorage_ x y) action =<< view (P.pantryConfigL.to P.pcStorage)
```suggestion
  storage <- view (P.pantryConfigL.to P.pcStorage)
  SQLite.withStorage_ storage action
```

Won't quite apply cleanly, needs a `do`. But I find this easier to read than the above. Can you also include a patch bump and changelog entry? Thanks!

2021-06-30 10:37 UTC, felixonmars commented on src/Pantry/Storage.hs
> +  flip (\x y -> SQLite.withStorage_ x y) action =<< view (P.pantryConfigL.to P.pcStorage)
Updated accordingly :)

2021-06-30 15:42 UTC, snoyberg approved these changes
Thank you!

2021-06-30 15:43 UTC, merged