Improve and expose `fetchRepos`/`fetchReposRaw`
commercialhaskell/pantry pull request #41
Opened 2021-09-30 21:43 UTC by hasufell

Necessary for https://github.com/commercialhaskell/stack/issues/5411

Please review this carefully. I don't understand most of pantry, but this seemed like the right place to inject and my manual tests succeeded.

Stack will then run `fetchReposRaw` at a specific place for pre-fetching. So we don't really change existing API.

2021-09-30 22:20 UTC, hasufell commented on src/Pantry/Repo.hs
> +          | length tids' == length aRepoSubdirs -> withStorage $ do
Here's one question: if we (for some odd reason) have less `tids'` and then select the branch below, executing `inner` instead... is there a chance we create duplicates?

2021-10-01 12:01 UTC, hasufell commented
One thing this doesn't solve is this: if you add a new subdirectory to an exising git extra-dep, it will have to clone once more. I'm not sure if there's a way around that.

2021-10-05 07:47 UTC, snoyberg requested changes
The overall logic looks really solid, impressive work here given your first work on this code base, thank you! I've left some comments inline.

2021-10-05 07:47 UTC, snoyberg commented on src/Pantry/Repo.hs
> +  logDebug (display . T.pack . show $ repos)
You can use `displayShow` here

2021-10-05 07:47 UTC, snoyberg commented on src/Pantry/Repo.hs
> +import Data.List (nub)
Generally [`nubOrd`](https://www.stackage.org/haddock/lts-18.12/rio-0.1.21.0/RIO-Prelude.html#v:nubOrd) is preferable to avoid quadratic complexity

2021-10-05 07:47 UTC, snoyberg commented on src/Pantry/Types.hs
> +  . filter (not . null)
Is there any possibility of a `null` coming through here? I think `groupBy` has an invariant that the output lists are all non-empty. This kind of thing would make sense for using a type-level witness such as `NonEmpty`, but otherwise I think this is a no-op.

2021-10-05 07:47 UTC, snoyberg commented on src/Pantry/Repo.hs
>  fetchRepos
If this (and `fetchReposRaw`) is now being exposed, it should get a Haddock comment with a `@since`.

2021-10-05 07:47 UTC, snoyberg commented on src/Pantry/Repo.hs
> +  => Text      -- ^ url
I don't feel strongly about this, but for more type safety, what about sending over the `AggregateRepo` instead so we can't accidentally switch `url` and `commit` positions? It may also make sense to have a separate type for the repo-without-subdir info. (Which, in retrospect, should have been `Repo`, but that ship has sailed.)

2021-10-05 07:47 UTC, snoyberg commented on src/Pantry/Repo.hs
> +        pure ((, subdir, rpm) <$> tid))
Not a major issue here, but it may be worth returning an `Either` value to distinguish cache hit from cache miss here. Then, in the lines below, you can use `partitionEithers` instead of the combo of `catMaybes` and the `filter`/`notElem` setup.

2021-10-05 11:25 UTC, hasufell commented on src/Pantry/Repo.hs
> +  => Text      -- ^ url
Yeah, I'm thinking

```hs
-- | Repository without subdirectory information.
--
-- @since 0.5.3
data SimpleRepo = SimpleRepo
  { sRepoUrl :: !Text
  , sRepoCommit :: !Text
  , sRepoType :: !RepoType
  }
```

2021-10-05 11:37 UTC, hasufell commented on src/Pantry/Repo.hs
> +        pure ((, subdir, rpm) <$> tid))
Excellent suggestion. That simplifies the code a lot.

2021-10-05 14:04 UTC, snoyberg reviewed
Looks great, one minor comment for consideration. I'm OK merging as is though, so let me know whether you think that change is worth it or not. If not, I'll merge/release in the current state.

2021-10-05 14:04 UTC, snoyberg commented on src/Pantry/Repo.hs
> +        loadRepoCache (Repo aRepoUrl aRepoCommit aRepoType subdir) subdir >>= \case
Nice!

2021-10-05 14:04 UTC, snoyberg commented on src/Pantry/Types.hs
> +data SimpleRepo = SimpleRepo
👍

2021-10-05 14:04 UTC, snoyberg commented on src/Pantry/Types.hs
> +  { aRepoUrl :: !Text
Not a strong recommendation, but what about using `SimpleRepo` here instead of duplicating the fields?

2021-10-05 14:20 UTC, hasufell commented on src/Pantry/Types.hs
> +  { aRepoUrl :: !Text
I'll give it a shot

2021-10-05 17:00 UTC, snoyberg approved these changes
LGTM!

2021-10-05 17:00 UTC, merged

2021-10-05 18:09 UTC, hasufell commented
@snoyberg thanks, the next step would be the actual stack PR that calls `fetchReposRaw` at the appropriate place: https://github.com/commercialhaskell/stack/pull/5624